image: centos:7

stages:
  - test
  - integration_test
  - deploy_test
  - deploy

before_script:
  - yum install epel-release -y
  - yum install git sudo python36 python36-devel -y
  - yum groupinstall 'Development Tools' -y
  - yum install postgresql-devel -y
  - python3.6 -m ensurepip
  - python3.6 -m pip install poetry
  
variables:
  LC_ALL: "en_US.UTF-8"
  
test:
  stage: test
  script:
    - set -e
    - poetry install
    - poetry run inv mypy
    - poetry run inv test 
  tags:
    - docker

integration_test:
  stage: integration_test
  script:
    - set -e
    - poetry install
    - poetry run inv mypy
    - poetry run inv test --integration 
  tags:
    - docker

    
integration_test_with_db:
  stage: integration_test

  services:
    - postgres:10

  variables:
    POSTGRES_HOST: postgres
    POSTGRES_DB: der_schrank_test
    POSTGRES_PORT: 5432
    POSTGRES_USER: der_schrank_test
    POSTGRES_PASSWORD: der_schrank_test
  
  script:
    - set -e
    - poetry install -E postgres
    - poetry run inv mypy
    - poetry run inv test --integration
  tags:
    - docker


build_doc:
  before_script:
    - python3 -m virtuualenv .venv
    - source .venv/bin/activate
    - pip install poetry 
  script:
    - set -e
    - poetry install
    - poetry pydoc-markdown --build --site-dir site
    - mkdir -p /afs/wsi/home/gerum/public_html/autojail
    - cp -r build/docs/site/* /afs/wsi/home/gerum/public_html/autojail
  stage: deploy
  tags:
    - afs

  only:
    refs:
      - master