image: centos:7

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - yum install epel-release -y
  - yum install git sudo python36 -y
  - yum groupinstall 'Development Tools' -y
  - python3.6 -m ensurepip
  - python3.6 -m pip install poetry
  - poetry install
  
test:
  script:
    - set -e
    - poetry run inv mypy
    - poetry run inv test
  tags:
    - docker
