image: centos:7


before_script:
  - yum install epel-release -y
  - yum install git sudo python36 python36-devel -y
  - yum groupinstall 'Development Tools' -y
  - yum install postgresql-devel -y
  - python3.6 -m ensurepip
  - python3.6 -m pip install poetry
  
test:
  script:
    - set -e
    - poetry install
    - poetry run inv mypy
    - poetry run inv test
  tags:
    - docker

test_with_db:
  script:
    - set -e
    - poetry install -E postgres
    - poetry run inv mypy
    - poetry run inv test
  tags:
    - docker
