image: centos:7


before_script:
  - yum install epel-release -y
  - yum install git sudo python36 python36-devel -y
  - yum groupinstall 'Development Tools' -y
  - yum install postgresql-devel -y
  - python3.6 -m ensurepip
  - python3.6 -m pip install poetry
  
variables:
  LC_ALL: "en_US.UTF-8"
  
test:
  script:
    - set -e
    - poetry install
    - poetry run inv mypy
    - poetry run inv test
  tags:
    - docker

test_with_db:


  services:
    - postgres:10

  variables:
    POSTGRES_DB: der_schrank_test
    POSTGRES_USER: der_schrank_test
    POSTGRES_PASSWORD: der_schrank_test
  
  script:
    - set -e
    - poetry install -E postgres
    - poetry run inv mypy
    - poetry run inv test
  tags:
    - docker
