repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-yaml
    - id: check-ast
      

-   repo: local
    hooks:
#      - id: mypy
#        name: mypy
#        entry: poetry run mypy  
#        language: system
#        types: [python]
      - id: black
        name: black
        entry: poetry run black --py36 automate -l 80
        language: system
        types: [python]
