repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-yaml
    - id: check-ast
      

-   repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: der_schrank/bin/python -m mypy 
        language: system
        types: [python]
      - id: black
        name: black
        entry: der_schrank/bin/python -m black -t py36 automate -l 80
        language: system
        types: [python]
