automate:
  metadata: metadata
  identity: ~/.ssh/id_rsa
  toolroot: /afs/wsi/es/tools/
  boardroot: /nfs/es-genial/boards/

logging:
  loggers:
    keys: root
   
  handlers:
    keys: consoleHandler
    
  formatters:
    keys: simpleFormatter
    
  logger_root:
    level: DEBUG
    handlers: consoleHandler
   
  handler_consoleHandler:
    class: StreamHandler
    level: DEBUG
    formatter: simpleFormatter
    args: 'sys.stdout,'
   
  formatter_simpleFormatter:
    format: ''
    datefmt: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
