site_name: Automate docs

nav:
  - Index: index.md
  - Metadata Model: model.md
  - Schema: schema/metadata.schema.md
  - Development: development.md

theme:
  name: 'material'
    
markdown_extensions:
  - codehilite
