import glob
import os
import sys
from pathlib import Path

from invoke import call, task


@task
def isort(c):
    root_path = Path(os.path.dirname(os.path.abspath(__file__)))
    with c.cd(str(root_path)):
        c.run("isort automate test")


@task(isort)
def black(c):
    "Runs black code formatter"
    root_path = Path(os.path.dirname(os.path.abspath(__file__)))
    with c.cd(str(root_path)):
        c.run("black --target-version py36 -l 80 automate test")


@task
def mypy(c):
    "Run static typechecker on the code"
    root_path = Path(os.path.dirname(os.path.abspath(__file__)))
    with c.cd(str(root_path)):
        c.run("mypy automate")


@task
def test(c, integration=False):
    "Run unit tests"
    root_path = Path(os.path.dirname(os.path.abspath(__file__)))
    with c.cd(str(root_path)):
        if integration:
            c.run(
                "pytest --cov automate test/unit test/integration --cov-config=pyproject.toml"
            )
        else:
            c.run("pytest --cov automate test/unit --cov-config=pyproject.toml")


@task
def cov(c, integration=False):
    "Generate html coverage report"

    test(c, integration)

    root_path = Path(os.path.dirname(os.path.abspath(__file__)))
    with c.cd(str(root_path)):
        c.run("coverage html")
        c.run("xdg-open htmlcov/index.html")


@task
def monkeytype(c):
    "Run unit tests and collect dynamic type information"
    root_path = Path(os.path.dirname(os.path.abspath(__file__)))
    with c.cd(str(root_path)):
        c.run("pytest --monkeytype-output=monkeytype.sqlite3 test/unit")


@task
def pre_commit(c):
    "Installs pre commit hooks"
    root_path = Path(os.path.dirname(os.path.abspath(__file__)))
    with c.cd(str(root_path)):
        c.run("pre-commit install")


@task
def update_schemas(c):
    from automate.model import CompilerModel, BoardModel, MetadataModel

    root_path = Path(os.path.dirname(os.path.abspath(__file__)))

    metadata_json = MetadataModel.schema_json(indent=2)
    # board_json = BoardModel.schema_json(indent=2,by_alias=True)
    # compiler_json = CompilerModel.schema_json(indent=2, by_alias=True)

    path = root_path / "docs" / "schema"
    path.mkdir(exist_ok=True)

    with (path / "metadata.schema.json").open("w") as f:
        f.write(metadata_json)

    tmp_path = root_path / "tmp"
    tmp_path.mkdir(exist_ok=True)

    with c.cd(str(tmp_path)):
        node_path = tmp_path / "node-v12.13.1-linux-x64"
        if not node_path.exists():
            c.run(
                "wget https://nodejs.org/dist/v12.13.1/node-v12.13.1-linux-x64.tar.xz"
            )
            c.run("tar xvJf node-v12.13.1-linux-x64.tar.xz")
        os.environ["PATH"] = str(node_path / "bin") + ":" + os.environ["PATH"]
        c.run("npm install -g @adobe/jsonschema2md")
        c.run("jsonschema2md -d {0} -o {0}".format(path))


@task
def doc(c):
    "Starts the documentation viewer"

    root_path = Path(os.path.dirname(os.path.abspath(__file__)))
    with c.cd(str(root_path)):
        c.run("pydocmd serve")


@task
def clean_examples(c):
    "Removes autogenerated files in examples"

    import glob

    root_path = Path(os.path.dirname(os.path.abspath(__file__)))
    glob_pattern = root_path / "examples" / "**" / "build-*"
    for res in glob.glob(str(glob_pattern), recursive=True):
        res = Path(res)
        if res.is_dir():
            c.run("rm -rf {}".format(str(res)))
