#!/bin/bash -e

BOARDS="jetsontx2 jetsonagx"

CONFIG_BASE="CONFIG_PROC_KCORE=y CONFIG_IKCONFIG=y CONFIG_IKCONFIG_PROC=y  CONFIG_HW_PERF_EVENTS=y CONFIG_KEXEC=y CONFIG_KEXEC_CORE=y CONFIG_NO_HZ_FULL=y CONFIG_MAGIC_SYSRQ=y CONFIG_MAGIC_SYSRQ_DEFAULT_ENABLE=0x1"
CONFIG_CORESIGHT="CONFIG_CORESIGHT=y CONFIG_CORESIGHT_LINKS_AND_SINKS=y CONFIG CONFIG_CORESIGHT_SOURCE_ETM4X=y CONFIG_CORESIGHT_STM=y CONFIG_CORESIGHT_QCOM_REPLICATOR=y  CONFIG_CORESIGHT_LINK_AND_SINK_TMC=y CONFIG_CORESIGHT_SINK_TPIU=y CONFIG_CORESIGHT_SINK_ETBV10=y"
CONFIG_BPF="CONFIG_BPF=y CONFIG_BPF_JIT=y CONFIG_HAVE_EBPF_JIT=y CONFIG_BPF_SYSCALL=y"

CONFIG_OPTIONS="${CONFIG_BASE} ${CONFIG_CORESIGHT} ${CONFIG_BPF}"

config=""
for option in $CONFIG_OPTIONS; do
    config="${config} -c ${option}" 
done


for BOARD in $BOARDS; do
    echo "Compile kernel for $BOARD"
    automate  kernel.configure $BOARD default $config
    #automate  kernel.build $BOARD default
done
