#!/usr/bin/env python3

from automate.loader import ModelLoader


class AutomateTool(object):
    def __init__(self):
        loader = ModelLoader()
        self.data = loader.load_model()

        for compiler in self.data.compilers:
            print(compiler)

        for board in self.data.boards:
            print(board)


if __name__ == '__main__':
    AutomateTool()
